language: go
env:
  - DEP_VERSION="0.5.0"
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure
script:
  - go test -v ./...